name: Continuous Integration

# This action works with pushes
on:
  push:
    branches:
      - dev
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
      - name: install eslint
        run: npm i

      - name: run ESLint
        run: npx eslint ./js/*.js

      - name: Unit tests
        run: npm test ./js/__tests__/unit.test.js
